package XString;

use strict;
use warnings;

# ABSTRACT: Isolated String helpers from B

BEGIN {

    # VERSION: generated by DZP::OurPkgVersion
    require XSLoader;
    XSLoader::load(__PACKAGE__);
}

=pod

=encoding utf-8

=head1 SYNOPSIS

# EXAMPLE: examples/synopsis.pl

=head1 DESCRIPTION

XString provides the L<B> string helpers in one isolated package.
Right now only L<cstring> and L<perlstring> are available.

=head1 FUNCTIONS

=head2 cstring(STR)

Similar to B::cstring;
Returns a double-quote-surrounded escaped version of STR which can
be used as a string in C source code.

=head2 perlstring(STR)

Similar to B::perlstring;
Returns a double-quote-surrounded escaped version of STR which can
be used as a string in Perl source code.

=cut

1;
