package XString;

use strict;
use warnings;

use Exporter 'import';

# ABSTRACT: Isolated String helpers from B

our @EXPORT_OK = qw(cstring perlstring);

BEGIN {

    # VERSION: generated by DZP::OurPkgVersion
    require XSLoader;
    XSLoader::load(__PACKAGE__);
}

=pod

=encoding utf-8

=begin markdown

[![CI](https://github.com/atoomic/XString/actions/workflows/ci.yml/badge.svg)](https://github.com/atoomic/XString/actions/workflows/ci.yml)

=end markdown

=head1 SYNOPSIS

# EXAMPLE: examples/synopsis.pl

=head1 DESCRIPTION

XString provides the L<B> string helpers in one isolated package.
Right now only L<cstring> and L<perlstring> are available.

Both functions can be imported individually:

    use XString qw(cstring perlstring);

or called fully qualified:

    use XString;
    XString::cstring($str);

=head1 FUNCTIONS

=head2 cstring(STR)

Similar to B::cstring;
Returns a double-quote-surrounded escaped version of STR which can
be used as a string in C source code.

=head2 perlstring(STR)

Similar to B::perlstring;
Returns a double-quote-surrounded escaped version of STR which can
be used as a string in Perl source code.

=cut

1;
