package XString;

use strict;
use warnings;

# ABSTRACT: Isolated String helpers from B

BEGIN {

    # VERSION: generated by DZP::OurPkgVersion
    require XSLoader;
    XSLoader::load(__PACKAGE__);
}

=pod

=over

=item cstring(STR)

Returns a double-quote-surrounded escaped version of STR which can
be used as a string in C source code.

=item perlstring(STR)

Returns a double-quote-surrounded escaped version of STR which can
be used as a string in Perl source code.

=back

=cut

1;
